  version: '3.0'

  services:
    app:
      build: .
      volumes:
        - './:/app'
      working_dir: /app
    webserver:
      ports:
        - '3005:80'
      image: nginx:1.22.0
    db:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=db
      ports:
        - '3306:3306'
      volumes:
        - "symfony-data:/var/lib/mysql"
  volumes:
    symfony-data:

